
env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created 
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "c1jx1BX8HdwQLiwCQEAssA"

language: cpp

dist: trusty
sudo: required

compiler:
  - g++

before_install:
  - sudo apt-get install doxygen 
  - sudo apt-get install libcunit1-dev 
  - sudo apt-get install libz-dev
  - sudo apt-get install libsctp-dev
  - sudo apt-get install libboost-all-dev
  - autoreconf -i

addons:
  coverity_scan:
  project:
    name: "open-nFAPI"
    decription: "Build submitted via Travis CS"
  build_command_prepend: "./configure && make"
  build_command: "make check"
  branch_pattern: coverity_scan

script:
  - ./configure && make && make check
