language: cpp

dist: trusty
sudo: required

compiler:
  - g++

addons:
	coverity_scan:

before_install:
  - sudo apt-get install doxygen 
  - sudo apt-get install libcunit1-dev 
  - sudo apt-get install libz-dev
  - sudo apt-get install libsctp-dev
  - sudo apt-get install libboost-all-dev
  - autoreconf -i

script:
  - ./configure && make && make check
