
env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created 
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "lKWPtp5VZhPr6z6azxragw"

language: cpp

dist: trusty
sudo: required

compiler:
  - g++

before_install:
  - sudo apt-get install doxygen 
  - sudo apt-get install libcunit1-dev 
  - sudo apt-get install libz-dev
  - sudo apt-get install libsctp-dev
  - sudo apt-get install libboost-all-dev
  - autoreconf -i

addons:
  coverity_scan:
    project:
      name: cisco/open-nFAPI
      version: 1.0
      description: Build submitted via Travis CI
    notification_email: xxx@cisco.com
    build_command_prepend: ./configure
    build_command: make
    branch_pattern: coverity_scan

script:
  - ./configure && make && make check
